### ISSUE TITLE
TCGA LUAD survival prediction result reproducing

### ISSUE THREAD

**Issue by Minsoo2022** [mahmoodlab/PANTHER#10]
Hi, thank you for the excellent work.

I am trying to reproduce the TCGA LUAD survival prediction performance from Table S1, which shows a C-Index of 0.672 using PANTHER ALL + linear + CTransPath. However, when I attempt to reproduce this experiment with your data split, I only achieve a C-Index of 0.6268 (mean of 5-fold cross-validation).

My hyperparameter settings are the same as in /src/scripts/survival/panther.sh, except for the feature extractor.

Could you please share the hyperparameter settings you used to achieve the reported results with CTransPath or suggest any ideas on how I might reproduce them?

**Comment by andrewsong90** [comment]
Hi @Minsoo2022 

The hyperparameter settings I used for the experiments did not change across different feature encoders, so what you see in `/src/scripts/survival/panther.sh` would be the one I used for CTP experiments.

For LUAD specifically, it might be that training on LUAD and LUSC combined (the whole NSCLC cohort, to boost the training dataset size) and then evaluating separately on LUAD and LUSC could help.

Best,
