### ISSUE TITLE
Some problems trying to make visualization step work

### ISSUE THREAD

**Issue by mathieudelattre** [mahmoodlab/PANTHER#13]
Hello

First of all thank you for your amazing work again on this new project !

I managed to run the first steps successfully, but I have a few small questions around the last step concerning visualization. I tried to run the notebook as explained in the readme however I faced some errors and I'm stuck there : 

**First error :**
```python
File ~/work/projets/EXP_PANTHER/PANTHER/src/visualization/../mil_models/PANTHER/layers.py:54, in PANTHERBase.__init__(self, d, p, L, tau, out, ot_eps, load_proto, proto_path, fix_proto)
     52     self.outdim = d
     53 else:
---> 54     raise NotImplementedError("Out mode {} not implemented".format(out))

NotImplementedError: Out mode param_cat not implemented

```

The out mode param_cat doesn't seem to exist when looking in the layers.py file. However there is another out_mode called 'weight_param_cat' so I naively remplaced it to avoid the NotImplementedError. Is this alright ? or is there a 'param_cat' out_mode existing and is it different from weight_param_cat ? 

(Another general question, is there somewhere we can find a description of each out mode and their best use case regarding the dataset used ?)

**Second error :**

```python
File ~/work/projets/EXP_PANTHER/PANTHER/src/visualization/../mil_models/PANTHER/layers.py:90, in PANTHERBase.forward(self, S, mask)
     88 out = []
---> 89 for h in range(self.H):
     90     pi, mu, Sigma = pis[..., h].reshape(B, -1), mus[..., h], Sigmas[..., h]
     91     mu_weighted = pi[..., None] * mu  # (n_batch, n_proto, instance_dim)

File ~/work/condagpu/envs/panther_vizu/lib/python3.9/site-packages/torch/nn/modules/module.py:1709, in Module.__getattr__(self, name)
   1707     if name in modules:
   1708         return modules[name]
-> 1709 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'PANTHERBase' object has no attribute 'H'
```

After overcoming the previous error by modifying the out mode, I face this one, where the attribute H doesn't exist for the PantherBase object. I checked in the attribute dict, and in the code in layers.py, I can't find a line mentionning the attribute H before this one.. I'm a little bit stucked there. What does the parameter H represent?

Thank you in advance for your help,
Best regards,

**Comment by andrewsong90** [comment]
Hello @mathieudelattre,

Thank you for your interest in PANTHER!

1. You should use `allcat`, as specified in this example [script](https://github.com/mahmoodlab/PANTHER/blob/main/src/scripts/embedding/panther.sh). `param_cat` was the terminology I used when developing PANTHER - I thought I had changed it completely, but if there were some parts of the code that led you to believe otherwise, I apologize.

I will try to clean up the code with explanation, but overall I found `allcat` to work quite well across the datasets. You can also try leaving out the covariance component (just keeping pi and mu) to reduce the dimension of the slide embedding, which also works quite well.

2. I was initially trying to develop multi-head version with `H` representing the number of heads. Since then I scrapped it and reverted to single-head version. So `self.H=1`. I will update the codebase soon and push it.

Thanks for helping point out parts of the code that needs to be cleaned up :)

**Comment by mathieudelattre** [comment]
Thx @andrewsong90 for your quick response ! 

Sorry to bother you again, following your answer I changed the out mode to `allcat` and set `self.H = 1`, however I'm facing a new issue then :

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 22
     20 print(out)
     21 tokenizer = PrototypeTokenizer(p=16)
---> 22 mus, pis, sigmas = tokenizer.forward(out)
     23 mus = mus[0].detach().cpu().numpy()
     24 qq = qqs[0,:,:,0].cpu().numpy()

File [~/work/projets/EXP_PANTHER/PANTHER/src/visualization/../mil_models/tokenizer.py:19](http://sv-ipc-hpcgpu-1:10002/lab/tree/work/projets/EXP_PANTHER/PANTHER/src/visualization/work/projets/EXP_PANTHER/PANTHER/src/mil_models/tokenizer.py#line=18), in PrototypeTokenizer.forward(self, X)
     17 def forward(self, X):
     18     print(X)
---> 19     n_samples = X.shape[0]
     20     if self.model_type == 'OT':
     21         if self.out_type == 'allcat':

AttributeError: 'str' object has no attribute 'shape'
```

I added a print in tokenizer.py to see what X was, the output is the string `repr`. I also added a print in the code in the visualization notebook : 
```python 
### get PANTHER representation and GMM mixtures
with torch.inference_mode():
    out, qqs = panther_encoder.representation(feats.unsqueeze(dim=0))
    print(out)
    tokenizer = PrototypeTokenizer(p=16)
    mus, pis, sigmas = tokenizer.forward(out)
```
which has also returned `repr`. So it seems that the line `out, qqs = panther_encoder.representation(feats.unsqueeze(dim=0))` doesn't return the representation desired ? 

Thank you in advance !
Best regards,

**Comment by Ycblue** [comment]
Hi, I'm also trying to get the code to work. 
I changed the line to 
```
out_dict = panther_encoder.representation(feats.unsqueeze(dim=0))
out = out_dict['repr']
qqs = out_dict['qq']
```
since `panther_encoder.representation` returns a dict instead of the actual values.
It works on my side, but the heatmaps still look weird.
Hope it helps!

**Comment by andrewsong90** [comment]
Hi @mathieudelattre,

Let me make fixes to the code over the weekend and push - I apologize for the inconvenience

Best,
