### ISSUE TITLE
val and test in the hyperparameter "split_names"

### ISSUE THREAD

**Issue by beidiz** [mahmoodlab/PANTHER#15]
Hi, I was wondering when do we need to involve the "val"/"test" in the hyperparameter "split_names"? I notice you only use train for prototyping, and the log file will only record the result on the training set.
When I add "val" in split_names in the downstream task, it shows 
```python
model_factory.py", line 159, in prepare_emb
    loader.dataset.X, loader.dataset.y = embeddings[k]['X'], embeddings[k]['y']
KeyError: 'val'
```

**Comment by andrewsong90** [comment]
Hi @mayonezu216 

For me to better understand the issue, can you let me know which settings you are using (etc. Cancer type, how you are splitting the data, etc.)?

**Comment by beidiz** [comment]
> Hi @mayonezu216
> 
> For me to better understand the issue, can you let me know which settings you are using (etc. Cancer type, how you are splitting the data, etc.)?

Hi @andrewsong90,

I am using survival test for TCGA-BRCA, just as the example script shown in the README.md file. The splitting is PANTHER/src/splits/survival/TCGA_BRCA_overall_survival_k=0.

**Comment by andrewsong90** [comment]
Hi @mayonezu216,

So the issue seems to be that in Step 2A "Unsupervised slide representation construction", the split_names for val was not created. Therefore the embeddings pkl file only has the keys "train" and "test", and when you try to add "val" as the split_name in `src/scripts/survival/brca_surv.sh`, it throws an error.

If you therefore specify "val" as the additional split name in `src/scripts/embedding/brca.sh`, I don't think you will have the issue. Having said that, since this is 5-fold CV, the `val.csv` and `test.csv` files should be identical. I will remove `val.csv` files to prevent any further confusion.

**Comment by mayonezu216** [comment]
Hi @andrewsong90,

I may not convey the question clearly. In src/scripts/prototype/brca.sh, split_names="train", then in src/scripts/embedding/brca.sh, split_names='train,test'. When I run embedding after prototyping, the KeyError will occur. I am a little confused whether we should use "test" in prototyping. 

Thanks!

**Comment by andrewsong90** [comment]
Hi @mayonezu216 

I think I saw your follow question on this issue through email, but it is strange that it doesn't show up here.

Yes in prototyping (clustering), I created prototypes based on the training dataset only, to prevent any forms of data leakage. Having said that, I tried creating prototypes based on the train and test dataset combined, and the performance did not change that much.

For creating unsupervised slide embedding for the test dataset, we then use the prototypes that were created based on training dataset.

You can also think of a possible extension where the prototypes are created only based on test dataset and then used only for creating slide embeddings for the test dataset.

Hope this helps

**Comment by beidiz** [comment]
Hi @andrewsong90,

Thanks so much! I think the bug was because I changed some code by mistake, so I deleted the follow question. I am happy to know that the result based on on the training and test dataset combined is similar to using only training dataset to do prototype. 

Sorry to bother you that I came up with a new question. What are the differences between "dss_" and "os_" in the dataset csv file? I notice if we use "os_", there will be 836 samples in the training data (fold 0 of BRCA), while the code uses "dss_" with only 817 samples in the training data. In other words, if we use "dss_", does it mean to rule out some patients?

Thanks again!

**Comment by andrewsong90** [comment]
Hi @mayonezu216 

DSS refers to disease-specific survival and OS refers to overall survival.
OS can include any kinds of death that can be non-cancer-related.
Therefore, we chose to go for DSS, which is more disease-specific.

For more information, you can check this paper
https://www.cell.com/cell/fulltext/S0092-8674(18)30229-0
