### ISSUE TITLE
Bug in clustering

### ISSUE THREAD

**Issue by HHHedo** [mahmoodlab/PANTHER#16]
Hi, 

After running the main_prototype, I found some unreasonable centroids (e.g.,  all zeros or almost the same centroids).
I think that [here](https://github.com/mahmoodlab/PANTHER/blob/6bc8477c967aecd09d842fd8b45c09a5eb483c89/src/utils/proto_utils.py#L83) is a bug, where the patches used for clustering should be   ```kmeans.train(patches[:n_patches].numpy())``` as used in the sklearn.cluster.

**Comment by andrewsong90** [comment]
Thank you @HHHedo !

That was my mistake, as I primarily relied on sklearn.cluster for the code development, only to add FAISS functionality later on. I will update the code accordingly
