### ISSUE TITLE
A question about the hyperparameter

### ISSUE THREAD

**Issue by beidiz** [mahmoodlab/PANTHER#18]
Hi @andrewsong90,

I am a little confused about the hyperparameter about the prototype number. In ./src/scripts/prototype/clustering.sh, n_sampling_patches=100000. However, in the example shown in README.md for prototyping and ./src/scripts/embedding/panther.sh, proto_num_samples='1.0e+06'. Could you please confirm the number in the experiment and provide this number for all datasets in the paper? 

Thanks!

**Comment by andrewsong90** [comment]
Hi @mayonezu216 

Apologies for the inconsistency - In my experience, beyond certain number, the prototypes do not change as much (marginal gain only). I would say go for higher number if your computing resources can handle them. So I would go for `proto_num_samples=1e6` (which would be 1.6e7 if you are using C=16)
