### ISSUE TITLE
Doubt regarding PANDA dataset

### ISSUE THREAD

**Issue by Rukhmini** [mahmoodlab/PANTHER#19]
Hello,

I am facing some problems hndling the PANDA dataset. How did you process the PANDA dataset? I see that in the splits section of the code for PANDA data train, val and test set have image_fn column which has the filename like this "024ed1244a6d817358cedaea3783bbde_x1672_y3836_w20587_h13031_crop.h5". Did you crop the tissue region from the whole slide images and then extracted the patches from the cropped region? TIA.

**Comment by andrewsong90** [comment]
Hi @Rukhmini 

Feel free to ignore `image_fn` this was an internally generated column from the tissue preprocessing code.
We used standard CLAM pipeline for segmenting and patching.

Best,
