### ISSUE TITLE
feature directory organization

### ISSUE THREAD

**Issue by RenlyH** [mahmoodlab/PANTHER#2]
Hi Song,

I appreciate you open source the code for this incredible work.

I wondering the how the feature directory look like. Specifically, what's FEAT_DIR_1? Is that all patch features in a certain WSI?

**Comment by andrewsong90** [comment]
Dear @RenlyH 

Thank you for your interest in PANTHER! I admit that the original explanation for feature_directory might have been slightly confusing. I updated the **README.md** to better explain this, so check it out!

In short, it's a directory ending with either `feats_h5` or `feats_pt` (depending on your preferred way of saving patch features). Each file in the directory would contain all patch features for a corresponding WSI. Therefore, if there are 100 WSIs in your cohort, the feature directory will have 100 files.

Let me know if this makes sense,
Best

**Comment by RenlyH** [comment]
Thanks for the reply and modification. 

I have one more followup: It looks like data_source allow multiple directories (FEAT_DIR_1, FEAT_DIR_2). And you will concat them to make a single dataset? Is there a specific reason to store those features separately? How do you store those WSI embeddings in these directories?

Thanks,
Best

**Comment by andrewsong90** [comment]
Allowing multiple directories was for maximum flexibility - In this case, yes these will be concatenated.
But in most of the use cases, you will deal with single feature directory (indicating same cancer cohort using same feature extractor), so only single directory is all you need!
