### ISSUE TITLE
prototype construction

### ISSUE THREAD

**Issue by wenhuihuang19791109** [mahmoodlab/PANTHER#21]
supposed I need to do inference for one slide, could you provide a infer code? I already have feature extraction from CLAM

**Comment by andrewsong90** [comment]
Hi @wenhuihuang19791109 

For this to properly work, You would need some set of slides in the _same_ cancer type for prototype construction.
Think of it as a training procedure for your typical MIL algorithm, where you would need a set of training slides to train your model.

Best,
