### ISSUE TITLE
Performance on Camelyon16

### ISSUE THREAD

**Issue by ElvinKim** [mahmoodlab/PANTHER#24]
Thank you for your amazing work.

Have you ever tried classifying Camelyon16 using PANTHER?

Despite using Uni features, the accuracy and AUC are around 0.85. Do you have any insights on why this might be the case?

With the same setup on this Repo, using ABMIL yielded accuracy and AUC of approximately 0.94 and 0.98, respectively.

**Comment by andrewsong90** [comment]
Hi @ElvinKim,

Yes we did try on Camelyon16 using PANTHER and I remember getting similar performance as what you had reported.
My hypothesis is PANTHER is not optimal for identifying a needle in the haystack problem.
I suggest trying PANTHER for other generic subtyping problems where each morphology is sufficiently prevalent.

Best,
Andrew
