### ISSUE TITLE
Confusion about pipeline

### ISSUE THREAD

**Issue by thomascong121** [mahmoodlab/PANTHER#25]
Thank you for the great work! I would like to use PANTHER to assign prototypes to patches. To achieve this, should I only run Step 1 for prototype construction? There’s no need to run the subsequent steps, is there? If that’s the case, could you clarify the role PANTHER plays in this process?

**Comment by andrewsong90** [comment]
Hi @thomascong121 

Yes, in this use case, you do not need to run subsequent steps of PANTHER. 
Simply assigning each patch to each prototype based on minimal distance to cluster centroid would be sufficient.

Of course, you can still use Step 2A. Once GMM is fitted, it will provide `qq` variable (posterior distribution of cluster assignment) that you can use to identify the cluster identity. For more inspiration, take a look at the [notebook ](https://github.com/mahmoodlab/PANTHER/blob/main/src/visualization/prototypical_assignment_map_visualization.ipynb)

Hope this helps
