### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by Rukhmini** [mahmoodlab/PANTHER#5]
Hello,
there are no files "create_downstream_model", "prepare_emb" in mil_models folder, line 21. from mil_models import create_downstream_model, prepare_emb in the trainer.py file.

**Comment by andrewsong90** [comment]
Hi @Rukhmini,

If you examine __init__.py in mil_models folder, you will see in line 14
`from .model_factory import create_downstream_model, prepare_emb`, which imports these methods from `model_factory.py`

Is running trainer.py raising ImportError?

Let me know

**Comment by Rukhmini** [comment]
I could find the files and give it a try. Thanks for the response.

**Comment by Rukhmini** [comment]
It will be really helpful if you let me know from where did you download the CPTAC (LUAD and LUSC) clinical table. TIA.

**Comment by andrewsong90** [comment]
You can find CPTAC data at TCIA website.
Note that the data is updated from time to time.

https://www.cancerimagingarchive.net/browse-collections/
