### ISSUE TITLE
Survival data in csv split

### ISSUE THREAD

**Issue by RenlyH** [mahmoodlab/PANTHER#6]
Hi Song,

I don't know how you collect the csv file in the survival splits. 

For example, in the TCGA-BRCA study, TCGA-A1-A0SK with os_censorship 0 and os_survival_days 967 cannot be found in the website page of this [case](https://portal.gdc.cancer.gov/cases/a5b44d66-c162-46b5-9df2-86305f0385c5). 

Can you share the information to collect those survival information? Since it's not described in the paper as well.

Thanks!

**Comment by andrewsong90** [comment]
Hi @RenlyH ,

If you look closely at the link you shared, you can find under **clinical** section that days to death is 2 years and 237 days, which is 967 days. There should be an option to download selected patients' clinical info as a .csv file

**Comment by RenlyH** [comment]
Hi,

I download tsv file from TCGA and compare the split in the repo. Those patients seems to have different survival day? Is there any other source provide these survival data?


| case_id | os_survival_days_TCGA|os_survival_days_panther |
| -------- |  ---------------------- | ------------------------- |
| TCGA-BH-A1F8	| 1 | 763|
|TCGA-AC-A3W6|0.0   |602.0|
|TCGA-AR-A1AJ|2383.0|3072.0|
|TCGA-B6-A0IH|2965.0|3418.0|
|TCGA-A2-A25D|0.0   |552.0|
|TCGA-C8-A26Y|0.0   |394.0|
|TCGA-D8-A1JK|0.0   |612.0|
|TCGA-LL-A6FP|0.0   |677.0|
|TCGA-BH-A18N|468.0 |1148.0|
|TCGA-E2-A9RU|0.0   |538.0|
|TCGA-OL-A66H|812.0 |NaN|
|TCGA-AC-A23H|0.0   |174.0|
|TCGA-A8-A08L|30.0  |304.0|
|TCGA-A2-A0CO|1468.0|3492.0|
|TCGA-B6-A0IC|0.0   |1542.0|
|TCGA-BH-A1FG|577.0 |3736.0|
|TCGA-LL-A5YM|394.0 |466.0|
|TCGA-E2-A15O|289.0 |1545.0|

**Comment by andrewsong90** [comment]
Hi @RenlyH,

Let me investigate this further and get back to you. 
We also referenced the following article (the supplementray table they provide) to obtain DSS endpoints
https://pubmed.ncbi.nlm.nih.gov/29625055/
