### ISSUE TITLE
WSIs at 20× magnification

### ISSUE THREAD

**Issue by Polycoriander** [mahmoodlab/PANTHER#7]
Hi，how do I know if the Whole Slide Images (WSIs) I am using are at 20× magnification?

**Comment by andrewsong90** [comment]
Hi @Polycoriander,

Please refer to API for OpenSlide - You can access pretty much all the information about WSI with this.

**Comment by Polycoriander** [comment]
> Hi @Polycoriander,
> 
> Please refer to API for OpenSlide - You can access pretty much all the information about WSI with this.

 If they are not at 20x magnification, how should they be handled? Is there corresponding code available for this?

**Comment by andrewsong90** [comment]
Hi @Polycoriander,

Yes, the standard patch creation & feature extraction code should be available from CLAM github repo
https://github.com/mahmoodlab/CLAM

For example, if you are requesting 256x256 px patch at 20x mag and it doesn't exist, you can create 512x512 px patch at 40x mag (usually one of the two magnifications always exists) and downsample it twice.

Hope it helps!

**Comment by Polycoriander** [comment]
> Hi @Polycoriander,
> 
> Yes, the standard patch creation & feature extraction code should be available from CLAM github repo https://github.com/mahmoodlab/CLAM
> 
> For example, if you are requesting 256x256 px patch at 20x mag and it doesn't exist, you can create 512x512 px patch at 40x mag (usually one of the two magnifications always exists) and downsample it twice.
> 
> Hope it helps!

Thank you for your answer！
For the TCGA LUAD dataset, I used 
```
slide = openslide.open_slide(dir) 
print(slide.properties) 
```
to get the magnification. Some WSI returned properties that included an aperio.AppMag key from which I could determine the magnification.
<img width="631" alt="2" src="https://github.com/user-attachments/assets/90cda191-9a87-4656-866d-6537b9943994">
 However, some do not have a key similar to aperio.AppMag. How can I obtain the magnification for these slides?
<img width="631" alt="3" src="https://github.com/user-attachments/assets/0cce742c-1535-4de6-aa77-ba0df506cd25">
