### ISSUE TITLE
Where is the GMM code?

### ISSUE THREAD

**Issue by weiaicunzai** [mahmoodlab/PANTHER#8]
Thanks for your work. Could you please tell me where is the GMM code? I only see the K-means code to perform prototype clustering.

**Comment by andrewsong90** [comment]
Hi @weiaicunzai 

You can access the entry code via [model_PANTHER.py](https://github.com/mahmoodlab/PANTHER/blob/main/src/mil_models/model_PANTHER.py)

For the actual code behind GMM, you can access them through the following [folder](https://github.com/mahmoodlab/PANTHER/tree/main/src/mil_models/PANTHER)

Hope this helps!
